# Generated by Django 4.1.7 on 2023-03-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(null=True)),
                ('token', models.TextField(null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
